name: API tests with Allure action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'   # 07:00 PL

jobs:
  api-tests-1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run API tests
        run: |
          mvn -pl java-selenium-test-automation-framework test \
            -Dsurefire.suiteXmlFiles=src/test/resources/testSuites/api/PET_STORE.xml \
            -Denvironment=ENV1 -Dplatform=api -Dapi.debug=false

      - name: Generate and publish Allure report
        uses: allure-framework/github-action@v3
        with:
          results-directories: java-selenium-test-automation-framework/allure-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          report-name: api-1
          publish-html: true
