name: UI tests (Playwright framework)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1'   # 08:00 PL

permissions:
  contents: write

jobs:
  ui-tests-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libxss1 libatk1.0-0 libcups2 libgbm1 \
            libgtk-4-1 libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libxext6 \
            libwoff1 libopus0 libwebp6 libflite1 libavif16 libharfbuzz-icu0 \
            libwayland-server0 libmanette-0.2-0 libhyphen0 libsecret-1-0 libgles2 libx264-163 \
            libgstgl-1.0-0 libgstcodecparsers-1.0-0 libgraphene-1.0-0

      - name: Run UI tests
        run: |
          mvn -pl java-playwright-test-automation-framework test \
          -Dsurefire.suiteXmlFiles=src/test/resources/testSuites/web/PHP_TRAVELS.xml \
          -Denvironment=ENV1 -Dplatform=web -Dweb.engine=firefox -Dweb.remote=false -Dweb.debug=false -Dweb.headless=true

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-ui-2
          path: java-playwright-test-automation-framework/allure-results
