name: UI tests for java-selenium-test-automation-framework

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 1'  # 07:30 PL

jobs:
  ui-tests-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run UI tests for java-selenium-test-automation-framework
        run: | 
         mvn -pl java-selenium-test-automation-framework test \
         -Dsurefire.suiteXmlFiles=src/test/resources/testSuites/web/PHP_TRAVELS.xml \
         -Denvironment=ENV1 -Dplatform=web -Dweb.browser=chrome -Dweb.grid=false -Dweb.debug=false -Dweb.headless=true

      - name: Upload Allure results (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-ui-1
          path: java-selenium-test-automation-framework/allure-results

      - name: Generate Allure HTML report
        if: always()
        run: |
          mvn allure:report -pl java-selenium-test-automation-framework
          mkdir -p allure-public/ui-1
          cp -r java-selenium-test-automation-framework/target/site/allure-maven-plugin/* allure-public/ui-1/

      - name: Deploy Allure report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-public